import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { prisma } from "./prisma.js";
import { sendVerificationEmail, sendPasswordResetEmail } from "./email.js";

export const auth = betterAuth({
    database: prismaAdapter(prisma, {
        provider: "postgresql",
    }),
    emailAndPassword: {
        enabled: true,
        requireEmailVerification: true,
        sendResetPassword: async ({ user, url }) => {
            // url is generated by better-auth, e.g. /reset-password?token=...
            await sendPasswordResetEmail(user.email, url);
        },
    },
    emailVerification: {
        sendVerificationEmail: async ({ user, url }) => {
            const frontendUrl = process.env.FRONTEND_URL || "http://localhost:3000";
            // আগের কোনো callbackURL থাকলে তা ফেলে দিয়ে নতুন করে আমাদের ফ্রন্টএন্ড লিঙ্ক সেট করা হচ্ছে
            const urlObj = new URL(url);
            urlObj.searchParams.set("callbackURL", `${frontendUrl}/login?message=Email verified successfully!`);

            await sendVerificationEmail(user.email, urlObj.toString());
        },
    },
    session: {
        expiresIn: 60 * 60 * 24 * 7, // 7 days
        updateAge: 60 * 60 * 24, // 1 day
    },
    trustedOrigins: [process.env.FRONTEND_URL || "http://localhost:3000"],
    user: {
        additionalFields: {
            role: { type: "string", defaultValue: "CUSTOMER" },
            status: { type: "string", defaultValue: "ACTIVE" },
            phone: { type: "string", required: false },
        }
    }
});
